"""
Data models for the Holded Invoice API.
"""

from .contact_groups import (
    ContactGroup,
    ContactGroupCreate,
    ContactGroupListResponse,
    ContactGroupResponse,
    ContactGroupUpdate,
)
from .contacts import (
    Contact,
    ContactAddress,
    ContactAttachment,
    ContactAttachmentListResponse,
    ContactAttachmentResponse,
    ContactAttachmentUpload,
    ContactBankAccount,
    ContactCreate,
    ContactImport,
    ContactImportResponse,
    ContactListParams,
    ContactListResponse,
    ContactPaymentSettings,
    ContactResponse,
    ContactSocialMedia,
    ContactStatus,
    ContactTax,
    ContactType,
    ContactUpdate,
)
from .documents import (
    Document,
    DocumentAttachment,
    DocumentAttachmentListResponse,
    DocumentAttachmentResponse,
    DocumentAttachmentUpload,
    DocumentCreate,
    DocumentItem,
    DocumentListParams,
    DocumentListResponse,
    DocumentPayment,
    DocumentPaymentCreate,
    DocumentPaymentListResponse,
    DocumentPaymentResponse,
    DocumentResponse,
    DocumentSendParams,
    DocumentSendResponse,
    DocumentStatus,
    DocumentStatusUpdate,
    DocumentTax,
    DocumentType,
    DocumentUpdate,
    PaymentMethod,
)
from .expense_accounts import (
    ExpenseAccount,
    ExpenseAccountCreate,
    ExpenseAccountListParams,
    ExpenseAccountListResponse,
    ExpenseAccountResponse,
    ExpenseAccountUpdate,
)
from .numbering_series import (
    NumberingSeries,
    NumberingSeriesCreate,
    NumberingSeriesListResponse,
    NumberingSeriesResponse,
    NumberingSeriesUpdate,
)
from .payments import (
    Payment,
    PaymentCreate,
    PaymentListParams,
    PaymentListResponse,
    PaymentResponse,
    PaymentUpdate,
)
from .products import (
    Product,
    ProductCategory,
    ProductCategoryCreate,
    ProductCategoryListParams,
    ProductCategoryListResponse,
    ProductCategoryResponse,
    ProductCategoryUpdate,
    ProductCreate,
    ProductImage,
    ProductImageListResponse,
    ProductImageResponse,
    ProductImageUpload,
    ProductImport,
    ProductImportResponse,
    ProductListParams,
    ProductListResponse,
    ProductResponse,
    ProductStatus,
    ProductStockAdjustment,
    ProductStockAdjustmentResponse,
    ProductSupplier,
    ProductTax,
    ProductType,
    ProductUpdate,
    ProductVariant,
    ProductVariantAttribute,
    ProductVariantListResponse,
    ProductVariantResponse,
    ProductWarehouse,
    StockManagement,
)
from .remittances import (
    Remittance,
    RemittanceListResponse,
    RemittanceResponse,
)
from .sales_channels import (
    SalesChannel,
    SalesChannelCreate,
    SalesChannelListParams,
    SalesChannelListResponse,
    SalesChannelResponse,
    SalesChannelUpdate,
)
from .services import (
    Service,
    ServiceCreate,
    ServiceListResponse,
    ServiceResponse,
    ServiceUpdate,
)
from .taxes import (
    Tax,
    TaxResponse,
)
from .treasury import (
    TreasuryAccount,
    TreasuryAccountCreate,
    TreasuryAccountListResponse,
    TreasuryAccountResponse,
)
from .warehouse import (
    Warehouse,
    WarehouseAddress,
    WarehouseCreate,
    WarehouseListParams,
    WarehouseListResponse,
    WarehouseResponse,
    WarehouseUpdate,
)

__all__ = [
    # Contacts
    "Contact",
    "ContactCreate",
    "ContactUpdate",
    "ContactAddress",
    "ContactBankAccount",
    "ContactTax",
    "ContactSocialMedia",
    "ContactPaymentSettings",
    "ContactType",
    "ContactStatus",
    "ContactListParams",
    "ContactAttachment",
    "ContactAttachmentUpload",
    "ContactImport",
    "ContactResponse",
    "ContactListResponse",
    "ContactAttachmentResponse",
    "ContactAttachmentListResponse",
    "ContactImportResponse",
    # Documents
    "DocumentType",
    "DocumentStatus",
    "PaymentMethod",
    "DocumentItem",
    "DocumentPayment",
    "DocumentTax",
    "DocumentCreate",
    "DocumentUpdate",
    "Document",
    "DocumentListParams",
    "DocumentSendParams",
    "DocumentAttachment",
    "DocumentAttachmentUpload",
    "DocumentPaymentCreate",
    "DocumentStatusUpdate",
    "DocumentResponse",
    "DocumentListResponse",
    "DocumentSendResponse",
    "DocumentAttachmentResponse",
    "DocumentAttachmentListResponse",
    "DocumentPaymentResponse",
    "DocumentPaymentListResponse",
    # Products
    "ProductType",
    "ProductStatus",
    "StockManagement",
    "ProductImage",
    "ProductVariantAttribute",
    "ProductVariant",
    "ProductTax",
    "ProductSupplier",
    "ProductWarehouse",
    "ProductCreate",
    "ProductUpdate",
    "Product",
    "ProductListParams",
    "ProductCategoryCreate",
    "ProductCategoryUpdate",
    "ProductCategory",
    "ProductCategoryListParams",
    "ProductStockAdjustment",
    "ProductImageUpload",
    "ProductImport",
    "ProductResponse",
    "ProductListResponse",
    "ProductCategoryResponse",
    "ProductCategoryListResponse",
    "ProductVariantResponse",
    "ProductVariantListResponse",
    "ProductStockAdjustmentResponse",
    "ProductImageResponse",
    "ProductImageListResponse",
    "ProductImportResponse",
    # Warehouse
    "WarehouseAddress",
    "WarehouseCreate",
    "WarehouseUpdate",
    "Warehouse",
    "WarehouseListParams",
    "WarehouseResponse",
    "WarehouseListResponse",
    # Treasury
    "TreasuryAccountCreate",
    "TreasuryAccount",
    "TreasuryAccountResponse",
    "TreasuryAccountListResponse",
    # Sales Channels
    "SalesChannelCreate",
    "SalesChannelUpdate",
    "SalesChannel",
    "SalesChannelListParams",
    "SalesChannelResponse",
    "SalesChannelListResponse",
    # Numbering Series
    "NumberingSeriesCreate",
    "NumberingSeriesUpdate",
    "NumberingSeries",
    "NumberingSeriesResponse",
    "NumberingSeriesListResponse",
    # Expense Accounts
    "ExpenseAccountCreate",
    "ExpenseAccountUpdate",
    "ExpenseAccount",
    "ExpenseAccountListParams",
    "ExpenseAccountResponse",
    "ExpenseAccountListResponse",
    # Remittances
    "Remittance",
    "RemittanceResponse",
    "RemittanceListResponse",
    # Payments
    "PaymentCreate",
    "PaymentUpdate",
    "Payment",
    "PaymentListParams",
    "PaymentResponse",
    "PaymentListResponse",
    # Taxes
    "Tax",
    "TaxResponse",
    # Contact Groups
    "ContactGroupCreate",
    "ContactGroupUpdate",
    "ContactGroup",
    "ContactGroupResponse",
    "ContactGroupListResponse",
    # Services
    "ServiceCreate",
    "ServiceUpdate",
    "Service",
    "ServiceResponse",
    "ServiceListResponse",
]
